language: node_js
cache:
  directories:
  - node_modules
node_js: stable
branches:
  only:
  - develop
addons:
  ssh_known_hosts:
  - "$DEPLOY_HOST"
before_install:
- openssl aes-256-cbc -K $encrypted_bb2d5a590d7b_key -iv $encrypted_bb2d5a590d7b_iv
  -in deploy_rsa.enc -out ~/.ssh/id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ~/.ssh/id_rsa
- ssh-add ~/.ssh/id_rsa
install:
- npm install
script:
- npm run build
after_success:
- rsync -rav dist/* "$DEPLOY_USER"@"$DEPLOY_HOST":/usr/local/nginx/html